name: Lambda Code Push
on:
  workflow_dispatch:

#on:
 # push:
  #  branches: 
   #   - develop
    #  - test
     # - prelive
      #- main
    #paths:
     # - '.github/workflows/iac_pull.yml'
      #- 'scripts/iac-*'
      #- 'scripts/tf-*'
      #- 'iac-scripts/**'

permissions:
  id-token: write
  contents: read

jobs:

  build-and-upload:
    name: Code Upload
    runs-on: ubuntu-latest
    concurrency:
      group: "${{ github.repository }}-${{ github.base_ref }}"
    environment: DEV #${{ (github.base_ref == 'main' && 'PRD') || 
    steps:
      - name: checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'

      - name: Install dependencies
        run: npm install --prefix ./s3-audit-service

      - name: Build TypeScript
        run: npm run build --prefix ./s3-audit-service

      - name: Zip function code
        run: |
          npm install --production --prefix ./s3-audit-service
          zip -r s3-audit-service.zip .
        working-directory: ./dist

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: eu-west-1

      - name: Upload to S3
        run: aws s3 cp ./dist/s3-audit-service.zip s3://dev-${{ secrets.S3_BUCKET_NAME }}/s3-audit-service.zip
